import type { Category, Flag, Prompt, StarterPack, Debrief } from './types';

export const categories: Category[] = [
  { id: 'communication', name: 'Communication', emoji: '🗣️', isDefault: true },
  { id: 'emotional', name: 'Emotional Intelligence', emoji: '💭', isDefault: true },
  { id: 'trust', name: 'Trust & Honesty', emoji: '🔐', isDefault: true },
  { id: 'safety', name: 'Safety & Boundaries', emoji: '🛡️', isDefault: true },
  { id: 'intimacy', name: 'Intimacy & Affection', emoji: '💕', isDefault: true },
  { id: 'lifestyle', name: 'Lifestyle & Habits', emoji: '🏠', isDefault: true },
  { id: 'money', name: 'Money & Finances', emoji: '💰', isDefault: true },
  { id: 'family', name: 'Family & Friends', emoji: '👨‍👩‍👧', isDefault: true },
  { id: 'ambition', name: 'Ambition & Effort', emoji: '🎯', isDefault: true },
  { id: 'little', name: 'The Little Things', emoji: '✨', isDefault: true },
  { id: 'bare', name: 'Bare Minimum', emoji: '🚨', isDefault: true },
];

export const flags: Flag[] = [
  // Red Flags
  {
    id: 'rf1',
    type: 'red',
    title: 'Makes me feel like I\'m too much',
    note: 'When I express my needs or feelings, he acts like I\'m being dramatic or needy',
    category: 'emotional',
    weight: 'dealbreaker',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'rf2',
    type: 'red',
    title: 'Doesn\'t ask about my life',
    note: 'Conversations are always about him. Rarely asks how I\'m doing or what\'s going on with me',
    category: 'communication',
    weight: 'dealbreaker',
    createdAt: new Date('2024-12-03'),
    updatedAt: new Date('2024-12-03'),
  },
  {
    id: 'rf3',
    type: 'red',
    title: 'Inconsistent texting',
    note: 'Hot and cold - super engaged one day, ghost the next',
    category: 'communication',
    weight: 'matters',
    createdAt: new Date('2024-12-05'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'rf4',
    type: 'red',
    title: 'Defensive when I bring up concerns',
    note: 'Can\'t handle feedback without getting upset or turning it around on me',
    category: 'emotional',
    weight: 'dealbreaker',
    createdAt: new Date('2024-12-08'),
    updatedAt: new Date('2024-12-08'),
  },
  {
    id: 'rf5',
    type: 'red',
    title: 'Rude to service staff',
    note: 'How he treats waiters/baristas says everything',
    category: 'bare',
    weight: 'dealbreaker',
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: 'rf6',
    type: 'red',
    title: 'Doesn\'t respect my boundaries',
    note: 'Pushes back when I say no or need space',
    category: 'safety',
    weight: 'dealbreaker',
    createdAt: new Date('2024-12-12'),
    updatedAt: new Date('2024-12-12'),
  },
  {
    id: 'rf7',
    type: 'red',
    title: 'Never apologizes first',
    note: 'Always waits for me to smooth things over',
    category: 'emotional',
    weight: 'matters',
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'rf8',
    type: 'red',
    title: 'Makes "jokes" that feel mean',
    note: 'Disguises criticism as humor, then says I can\'t take a joke',
    category: 'communication',
    weight: 'dealbreaker',
    createdAt: new Date('2024-12-18'),
    updatedAt: new Date('2024-12-18'),
  },

  // Green Flags
  {
    id: 'gf1',
    type: 'green',
    title: 'Remembers things I\'ve told him',
    note: 'Brings up details from previous conversations - shows he actually listens',
    category: 'communication',
    weight: 'matters',
    createdAt: new Date('2024-12-02'),
    updatedAt: new Date('2024-12-02'),
  },
  {
    id: 'gf2',
    type: 'green',
    title: 'Takes accountability',
    note: 'Actually says "I\'m sorry" without making excuses',
    category: 'emotional',
    weight: 'dealbreaker',
    createdAt: new Date('2024-12-04'),
    updatedAt: new Date('2024-12-04'),
  },
  {
    id: 'gf3',
    type: 'green',
    title: 'Consistent communication',
    note: 'Responds within a reasonable time, doesn\'t leave me guessing',
    category: 'communication',
    weight: 'matters',
    createdAt: new Date('2024-12-06'),
    updatedAt: new Date('2024-12-06'),
  },
  {
    id: 'gf4',
    type: 'green',
    title: 'Plans thoughtful dates',
    note: 'Puts effort into making plans, not just "wanna hang?"',
    category: 'little',
    weight: 'bonus',
    createdAt: new Date('2024-12-09'),
    updatedAt: new Date('2024-12-09'),
  },
  {
    id: 'gf5',
    type: 'green',
    title: 'Supports my goals',
    note: 'Gets excited about my wins and encourages me',
    category: 'ambition',
    weight: 'matters',
    createdAt: new Date('2024-12-11'),
    updatedAt: new Date('2024-12-11'),
  },
  {
    id: 'gf6',
    type: 'green',
    title: 'Respects when I need space',
    note: 'Doesn\'t take it personally when I need alone time',
    category: 'safety',
    weight: 'matters',
    createdAt: new Date('2024-12-14'),
    updatedAt: new Date('2024-12-14'),
  },
  {
    id: 'gf7',
    type: 'green',
    title: 'Kind to everyone',
    note: 'Treats waiters, strangers, and friends with the same respect',
    category: 'bare',
    weight: 'dealbreaker',
    createdAt: new Date('2024-12-16'),
    updatedAt: new Date('2024-12-16'),
  },
  {
    id: 'gf8',
    type: 'green',
    title: 'Emotionally available',
    note: 'Comfortable talking about feelings and being vulnerable',
    category: 'emotional',
    weight: 'matters',
    createdAt: new Date('2024-12-19'),
    updatedAt: new Date('2024-12-19'),
  },
];

export const prompts: Prompt[] = [
  // Communication
  {
    id: 'p1',
    text: 'How do you want to be spoken to when he\'s frustrated?',
    category: 'communication',
    depth: 'deep',
    isCompleted: false,
  },
  {
    id: 'p2',
    text: 'What does it feel like when someone actually listens to you?',
    category: 'communication',
    depth: 'medium',
    isCompleted: true,
  },
  {
    id: 'p3',
    text: 'What\'s a texting habit that immediately turns you off?',
    category: 'communication',
    depth: 'light',
    isCompleted: false,
  },

  // Emotional Intelligence
  {
    id: 'p4',
    text: 'How should he respond when you\'re upset about something he did?',
    category: 'emotional',
    depth: 'deep',
    isCompleted: false,
  },
  {
    id: 'p5',
    text: 'What does accountability actually look like to you?',
    category: 'emotional',
    depth: 'deep',
    isCompleted: true,
  },
  {
    id: 'p6',
    text: 'Describe a time a man made you feel emotionally safe.',
    category: 'emotional',
    depth: 'deep',
    isCompleted: false,
  },

  // Safety & Boundaries
  {
    id: 'p7',
    text: 'How does he handle hearing "no"?',
    category: 'safety',
    depth: 'deep',
    isCompleted: false,
  },
  {
    id: 'p8',
    text: 'Have you ever felt physically tense around someone? What triggered it?',
    category: 'safety',
    depth: 'deep',
    isCompleted: false,
  },
  {
    id: 'p9',
    text: 'What\'s a boundary you\'ve let slide before that you won\'t again?',
    category: 'safety',
    depth: 'deep',
    isCompleted: false,
  },

  // Trust & Honesty
  {
    id: 'p10',
    text: 'What\'s a lie you\'ve made excuses for?',
    category: 'trust',
    depth: 'deep',
    isCompleted: false,
  },
  {
    id: 'p11',
    text: 'How do you want to feel about his phone?',
    category: 'trust',
    depth: 'medium',
    isCompleted: false,
  },
  {
    id: 'p12',
    text: 'What does trust look like in action, not just words?',
    category: 'trust',
    depth: 'deep',
    isCompleted: false,
  },

  // The Little Things
  {
    id: 'p13',
    text: 'What small gesture makes you feel genuinely cared for?',
    category: 'little',
    depth: 'medium',
    isCompleted: false,
  },
  {
    id: 'p14',
    text: 'What "ick" is actually a red flag in disguise?',
    category: 'little',
    depth: 'light',
    isCompleted: false,
  },
  {
    id: 'p15',
    text: 'What effort do you want to stop calling "extra"?',
    category: 'little',
    depth: 'medium',
    isCompleted: false,
  },

  // Reflection Prompts
  {
    id: 'p16',
    text: 'What did you tolerate in your last relationship that you\'re done with?',
    category: 'emotional',
    depth: 'deep',
    isCompleted: false,
  },
  {
    id: 'p17',
    text: 'What\'s something you used to think was normal but now recognize as a red flag?',
    category: 'emotional',
    depth: 'deep',
    isCompleted: false,
  },
  {
    id: 'p18',
    text: 'If your best friend described this situation, what would you tell her?',
    category: 'emotional',
    depth: 'deep',
    isCompleted: false,
  },
];

export const starterPacks: StarterPack[] = [
  {
    id: 'sp1',
    name: 'The Bare Minimum',
    description: 'Green flags that should be standard (but somehow aren\'t)',
    flags: [
      {
        type: 'green',
        title: 'Responds to texts within reasonable time',
        category: 'bare',
        weight: 'matters',
      },
      {
        type: 'green',
        title: 'Remembers things you\'ve told him',
        category: 'bare',
        weight: 'matters',
      },
      {
        type: 'green',
        title: 'Doesn\'t make you feel crazy',
        category: 'bare',
        weight: 'dealbreaker',
      },
      {
        type: 'green',
        title: 'Shows up when he says he will',
        category: 'bare',
        weight: 'matters',
      },
      {
        type: 'green',
        title: 'Treats service staff with respect',
        category: 'bare',
        weight: 'dealbreaker',
      },
    ],
  },
  {
    id: 'sp2',
    name: 'Love Bombing 101',
    description: 'Red flags disguised as romance',
    flags: [
      {
        type: 'red',
        title: 'Too intense too fast',
        note: 'Saying "I love you" within weeks, planning the future immediately',
        category: 'safety',
        weight: 'dealbreaker',
      },
      {
        type: 'red',
        title: 'Future-faking',
        note: 'Makes grand promises about the future that never materialize',
        category: 'trust',
        weight: 'dealbreaker',
      },
      {
        type: 'red',
        title: 'Isolating you from friends',
        note: 'Wants all your time, makes you feel guilty for seeing friends',
        category: 'safety',
        weight: 'dealbreaker',
      },
      {
        type: 'red',
        title: 'Over-the-top grand gestures',
        note: 'But no consistent small acts of care',
        category: 'little',
        weight: 'matters',
      },
    ],
  },
  {
    id: 'sp3',
    name: 'Icks That Are Actually Red Flags',
    description: 'Things we laugh off but shouldn\'t',
    flags: [
      {
        type: 'red',
        title: 'Never apologizes',
        note: 'Or says "sorry you feel that way"',
        category: 'emotional',
        weight: 'dealbreaker',
      },
      {
        type: 'red',
        title: 'Jokes that are actually mean',
        note: 'Then says you\'re too sensitive',
        category: 'communication',
        weight: 'dealbreaker',
      },
      {
        type: 'red',
        title: '"I\'m not like other guys"',
        note: 'Proceeds to be exactly like other guys',
        category: 'communication',
        weight: 'matters',
      },
      {
        type: 'red',
        title: 'Brags about bare minimum',
        note: '"I\'ve never cheated" or "I have a job" as selling points',
        category: 'bare',
        weight: 'matters',
      },
    ],
  },
  {
    id: 'sp4',
    name: 'Emotional Maturity Green Flags',
    description: 'What regulated actually looks like',
    flags: [
      {
        type: 'green',
        title: 'Takes space without stonewalling',
        note: 'Says "I need time to process, let\'s talk tomorrow"',
        category: 'emotional',
        weight: 'matters',
      },
      {
        type: 'green',
        title: 'Owns mistakes without deflecting',
        note: 'No "but you..." or excuses',
        category: 'emotional',
        weight: 'dealbreaker',
      },
      {
        type: 'green',
        title: 'Supports your success',
        note: 'Never threatened by your wins',
        category: 'ambition',
        weight: 'matters',
      },
      {
        type: 'green',
        title: 'Can talk about feelings',
        note: 'Doesn\'t shut down when things get emotional',
        category: 'emotional',
        weight: 'matters',
      },
    ],
  },
];

export const debriefs: Debrief[] = [
  {
    id: 'd1',
    personName: 'Jake',
    dateNumber: 1,
    date: new Date('2024-12-20'),
    overallVibe: 3,
    triggeredFlagIds: ['rf3', 'gf1', 'gf4'],
    notes: 'Dinner was nice, he planned it which was sweet. But his texting before the date was all over the place.',
    wouldRecommendDate2: true,
    createdAt: new Date('2024-12-20'),
  },
  {
    id: 'd2',
    personName: 'Jake',
    dateNumber: 2,
    date: new Date('2024-12-27'),
    overallVibe: 2,
    triggeredFlagIds: ['rf2', 'rf3', 'rf7'],
    notes: 'He talked about himself the whole time. Asked me like two questions. Starting to see a pattern.',
    wouldRecommendDate2: false,
    createdAt: new Date('2024-12-27'),
  },
  {
    id: 'd3',
    personName: 'Chris',
    dateNumber: 1,
    date: new Date('2025-01-03'),
    overallVibe: 4,
    triggeredFlagIds: ['gf2', 'gf3', 'gf5', 'gf7', 'gf8'],
    notes: 'This felt different. He was genuinely interested, asked thoughtful questions, made me laugh. No games.',
    wouldRecommendDate2: true,
    createdAt: new Date('2025-01-03'),
  },
  {
    id: 'd4',
    personName: 'Marcus',
    dateNumber: 1,
    date: new Date('2025-01-05'),
    overallVibe: 1,
    triggeredFlagIds: ['rf5', 'rf8'],
    notes: 'Yikes. Rude to the waiter, made weird comments about my outfit. Hard pass.',
    wouldRecommendDate2: false,
    createdAt: new Date('2025-01-05'),
  },
];
